# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: php:8.1-fpm

definitions:
  steps:
    - step: &build
        name: Build
        script:
          - apt-get update && apt-get install -qy unzip git curl
          - apt-get clean -y
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --optimize-autoloader --no-interaction --prefer-dist
          - ln -f -s .env.pipelines .env
          - ./vendor/bin/phpunit
        caches:
          - composer
        artifacts:
          - vendor/**
pipelines:
  default:
    - step: *build
